import React, { Component } from 'react';
import Layout from '../components/Layout';
import { Router } from '../routes';
import style from '../styles/PrivacyPolicy.module.css';

export default class PrivacyPolicy extends Component {
	render() {
		return (
			<Layout>
				<div className={style.main_container}>
					<h2>Privacy Policy (Dummy Text)</h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam velit odio, efficitur sed pellentesque non, tempus eget erat. Sed libero felis, placerat sit amet consequat id, iaculis at arcu. Aliquam erat volutpat. Phasellus mi justo, tempus dapibus metus id, hendrerit sodales magna. In lobortis, sapien vitae egestas posuere, felis tortor dictum sapien, eu vehicula sem augue nec risus. Integer mollis rhoncus tincidunt. Aenean hendrerit vitae lectus at aliquet. Etiam eleifend fringilla ante eu aliquet. Curabitur laoreet ex congue, pharetra arcu a, tempus lorem. Nam et leo in nunc aliquam lacinia varius nec augue. Duis eu velit eu ex scelerisque sodales. Pellentesque finibus massa at elit volutpat iaculis. Suspendisse fermentum luctus fermentum. Praesent fringilla cursus diam in commodo. Pellentesque convallis viverra metus, eget posuere odio euismod vel. Integer ultricies convallis posuere.</p>
					<p>Donec vehicula faucibus sem ut dignissim. Aenean sit amet diam congue nisi aliquam fermentum. Etiam interdum egestas tellus, in molestie nulla semper nec. Aenean luctus eros enim, et posuere neque dapibus ut. Nulla congue laoreet enim, quis tempor erat feugiat quis. Sed porttitor erat sit amet justo aliquam fringilla. In gravida sollicitudin neque, a suscipit nunc tristique eget. Aliquam enim magna, egestas in ultricies at, dictum ac nibh. Quisque nec justo et sapien elementum egestas. Mauris sed feugiat mi, eu mattis neque.</p>
					<p>Sed vitae tincidunt libero. Praesent lobortis, nisl non accumsan ornare, enim ligula eleifend orci, vel cursus quam nulla nec nibh. Fusce facilisis sed tortor faucibus eleifend. Integer fringilla mi eget risus consectetur sagittis. Sed sit amet varius risus, sed ornare urna. Proin iaculis vulputate hendrerit. Curabitur enim purus, dapibus ut suscipit et, lobortis at augue. Nam justo nisl, porta et interdum nec, faucibus sed velit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam iaculis, mauris quis laoreet hendrerit, orci tellus venenatis ipsum, in semper dolor tortor ac augue. Donec ultricies, lacus ac blandit consectetur, ex lacus tempus enim, ac pretium tellus velit id ante. Praesent in finibus nibh. Nam pulvinar, tortor sagittis tincidunt finibus, ligula purus facilisis justo, vel aliquam lectus ipsum et leo. Proin tempor condimentum mauris. Praesent at consectetur leo.</p>
					<p>Aliquam at enim a sapien porttitor rutrum. Nullam viverra efficitur orci ac tempor. Aliquam varius leo libero, sed egestas arcu elementum eu. Phasellus cursus risus vel congue feugiat. Nunc pulvinar congue vulputate. Proin vitae pharetra libero. Proin accumsan in tortor vel finibus. Nunc convallis turpis eu sem lacinia scelerisque. Maecenas non sapien malesuada, lacinia urna vel, gravida diam. Nulla porta, diam at mollis viverra, quam leo ullamcorper ligula, vitae congue orci ipsum sit amet mauris. Nam facilisis sollicitudin varius. Quisque aliquam a nisi nec dignissim. Morbi commodo ligula at quam cursus, id iaculis nulla malesuada.</p>
					<p>Pellentesque rhoncus, sem non interdum fermentum, massa odio lobortis dolor, nec volutpat ex ante quis mauris. Morbi non efficitur dolor, vel aliquam turpis. Curabitur gravida elit vel nisi viverra, vel pulvinar ante cursus. Ut sollicitudin faucibus sapien. Etiam quis nisi in lorem suscipit consequat. Maecenas nec turpis vel tellus efficitur blandit. Duis et pretium orci. Maecenas nec gravida elit. Ut sagittis justo non imperdiet vulputate. Nullam arcu risus, laoreet ut sapien quis, convallis sagittis mi. Donec ligula tellus, iaculis a mauris sollicitudin, accumsan ultrices ipsum. Quisque efficitur efficitur est sit amet efficitur.</p>
					<p>Morbi quis lacus maximus, rutrum nisi ac, consectetur lacus. Proin eget tempus dolor. Sed dolor dui, auctor et suscipit eu, vestibulum eget felis. Sed sed mollis tellus, vel suscipit sem. Suspendisse vestibulum magna velit, eu sagittis quam lobortis vel. Sed facilisis dictum ornare. Maecenas blandit, metus nec hendrerit auctor, sapien libero posuere ligula, ut sodales elit tortor eget felis. Donec urna magna, varius ut rutrum blandit, pretium id erat. Duis molestie efficitur bibendum. Integer sit amet varius nisl. Sed pulvinar id eros in tincidunt. Phasellus vel sapien id sem gravida tempor eu vel risus. Mauris sit amet velit arcu.</p>
					<p>Praesent at dolor nisi. In pharetra, ligula at lacinia tempus, magna risus feugiat mi, quis pretium quam ante a ante. Ut aliquam scelerisque blandit. Donec ultrices, felis a ultricies consequat, lorem risus lobortis neque, ultricies pharetra erat odio ultricies elit. Aliquam erat volutpat. Morbi ipsum neque, molestie sed eros imperdiet, bibendum dignissim nisl. Phasellus tincidunt porttitor dui, tempus sodales lacus finibus ut. Phasellus libero neque, vestibulum at mauris sed, accumsan blandit eros. Mauris porta faucibus arcu, sed placerat nunc pretium ut. Curabitur consectetur varius blandit.</p>
					<p>Phasellus ut eros molestie, malesuada mi sit amet, interdum eros. Nulla vel lectus eros. Sed dignissim massa erat, sit amet ultricies lacus tempus vitae. Fusce eget enim nulla. Donec id accumsan nibh. Vestibulum sem ipsum, laoreet eu dignissim quis, auctor nec neque. Proin vitae quam sodales, vulputate mauris id, mollis odio. Donec sagittis, ex suscipit euismod malesuada, ipsum nunc tincidunt nisl, et ullamcorper eros metus consequat magna.</p>
					<p>Duis in lorem efficitur, varius eros nec, malesuada lorem. Donec ut nibh tellus. Proin venenatis ligula nulla, imperdiet ultrices urna pretium id. Maecenas a lectus tincidunt nisi rutrum cursus vitae vitae lacus. Donec enim dolor, tempor quis mi sed, ultrices porta libero. Vestibulum malesuada leo ac sapien fermentum fermentum. Quisque vulputate accumsan mauris id molestie. Aliquam erat sem, sodales sed risus quis, ullamcorper sollicitudin felis. Nulla facilisi. Aliquam aliquam lacus nisi, non pharetra nisi blandit id.</p>
				</div>
			</Layout>
		)
	}
}